export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const FETCH_INITIAL_INGREDIENTS_SUCCESS = 'FETCH_INITIAL_INGREDIENTS_SUCCESS';
export const FETCH_INITIAL_INGREDIENTS_FAIL = 'FETCH_INITIAL_INGREDIENTS_FAIL';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_START = 'PURCHASE_START';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const SIGNUPORIN_START = 'SIGNUPORIN_START';
export const SIGNUPORIN_SUCCESS = 'SIGNUPORIN_SUCCESS';
export const SIGNUPORIN_FAIL = 'SIGNUPORIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const SET_AUTH_PATH = 'SET_AUTH_PATH';
